name: Shellcheck

on:
  push:
    branches:
      - '*'
    paths:
      - '*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches:
      - dev
    paths:
      - '*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run Shellcheck
        run: shellcheck -V && shellcheck -e SC2164 -e SC2034 -e SC2181 -e SC2089 -e SC1091 *.sh && echo "shellcheck OK"
